---
- hosts: webserver
  become: yes
  tasks:
    - name: Ensure Docker is running
      service:
        name: docker
        state: started

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ playbook_dir }}/.."
        name: express-app
        source: build
        force_source: yes

    - name: Run Docker container
      docker_container:
        name: express-app
        image: express-app
        state: started
        recreate: yes
        published_ports:
          - "8080:8080"
